---
title: "Introduction"
author: "Mauricio Campos"
date: "19 de diciembre de 2017"
output:
  pdf_document: default
  html_document: default
---

## Data Background

```{r}
library(here)
listings <- read.csv(here("data", "listings.csv"), header = T)
```


The data was taken from the website insideairbnb.com, which is an independent entity from Airbnb that lets you explore data from certain cities around the world. The data that the compile in their website is publicly available information. The data set for Venice was released in partnership with RESET VENEZIA, a group of local activists that strive to use data for the benefit of the local communities in Venice. The data was compiled on May 9th 2017 and has `r nrow(listings)` listings and `r ncol(listings)` variables. 

Of the `r ncol(listings)` variables, 4 represent ID variables and the rest have potential use in a linear model. These are: neighbourhood group, neihbourhood, latitude, longitude, room type, price, minimum nights, number of reviews, date of the last review, reviews per month, calculated host listings count and days available in a year. Date of the last review was not taken into account since not all listings had reviews and number or reviews or reviews per month could be a much more powerfull predictive variable in a future model. Another variable that was discarded early on was the calculated host listings count which specified, for each host, the estimated number of listings that entity had. Since this variable describes best the host instead of the listing we decided to not use it in the model. 

There were `r sum(is.na(listings))` NA's in the dataset, however they were all in the variable reviews per month. By doing carefull analysis of the dataset it was discovered that all the NA's corresponded to listings with zero reviews so the NA's were changed into zeroes. 
